.TH "/home/stephan/code/unversioned/mdcore-0.1.7/src/angle.c" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephan/code/unversioned/mdcore-0.1.7/src/angle.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./config\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'cycle\&.h'\fP
.br
\fC#include 'errs\&.h'\fP
.br
\fC#include 'fptype\&.h'\fP
.br
\fC#include 'lock\&.h'\fP
.br
\fC#include 'part\&.h'\fP
.br
\fC#include 'potential\&.h'\fP
.br
\fC#include 'potential_eval\&.h'\fP
.br
\fC#include 'cell\&.h'\fP
.br
\fC#include 'space\&.h'\fP
.br
\fC#include 'engine\&.h'\fP
.br
\fC#include 'angle\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBerror\fP(\fBid\fP)   ( \fBangle_err\fP = \fBerrs_register\fP( \fBid\fP , \fBangle_err_msg\fP[-(\fBid\fP)] , __LINE__ , __FUNCTION__ , __FILE__ ) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBangle_eval\fP (struct \fBangle\fP *a, int N, struct \fBengine\fP *\fBe\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of angleed interactions\&. \fP"
.ti -1c
.RI "int \fBangle_evalf\fP (struct \fBangle\fP *a, int N, struct \fBengine\fP *\fBe\fP, \fBFPTYPE\fP *\fBf\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of angleed interactions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBangle_err\fP = \fBangle_err_ok\fP"
.br
.ti -1c
.RI "unsigned int \fBangle_rcount\fP = 0"
.br
.ti -1c
.RI "char * \fBangle_err_msg\fP [2]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define error(\fBid\fP)   ( \fBangle_err\fP = \fBerrs_register\fP( \fBid\fP , \fBangle_err_msg\fP[-(\fBid\fP)] , __LINE__ , __FUNCTION__ , __FILE__ ) )"

.SH "Function Documentation"
.PP 
.SS "int angle_eval (struct \fBangle\fP *a, intN, struct \fBengine\fP *e, double *epot_out)"

.PP
Evaluate a list of angleed interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBangle\fP\&. 
.br
\fIN\fP Nr of angles in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these angles are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBangle_err_ok\fP or <0 on error (see \fBangle_err\fP) 
.RE
.PP

.SS "int angle_evalf (struct \fBangle\fP *a, intN, struct \fBengine\fP *e, \fBFPTYPE\fP *f, double *epot_out)"

.PP
Evaluate a list of angleed interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBangle\fP\&. 
.br
\fIN\fP Nr of angles in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these angles are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
This function differs from \fBangle_eval\fP in that the forces are added to the array \fCf\fP instead of directly in the particle data\&.
.PP
\fBReturns:\fP
.RS 4
\fBangle_err_ok\fP or <0 on error (see \fBangle_err\fP) 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int angle_err = \fBangle_err_ok\fP"
The ID of the last error\&. 
.SS "char* angle_err_msg[2]"
\fBInitial value:\fP
.PP
.nf
= {
        "Nothing bad happened\&.",
    "An unexpected NULL pointer was encountered\&."
        }
.fi
.SS "unsigned int angle_rcount = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
