.TH "/Users/stephan/Code/git/mdcore/src/angle.h" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/stephan/Code/git/mdcore/src/angle.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBangle\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBangle_err_ok\fP   0"
.br
.ti -1c
.RI "#define \fBangle_err_null\fP   -1"
.br
.ti -1c
.RI "#define \fBangle_err_malloc\fP   -2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBangle_eval\fP (struct \fBangle\fP *a, int N, struct \fBengine\fP *\fBe\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of angleed interactions\&. \fP"
.ti -1c
.RI "int \fBangle_evalf\fP (struct \fBangle\fP *a, int N, struct \fBengine\fP *\fBe\fP, \fBFPTYPE\fP *\fBf\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of angleed interactions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBangle_err\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define angle_err_malloc   -2"

.SS "#define angle_err_null   -1"

.SS "#define angle_err_ok   0"

.SH "Function Documentation"
.PP 
.SS "int angle_eval (struct \fBangle\fP *a, intN, struct \fBengine\fP *e, double *epot_out)"

.PP
Evaluate a list of angleed interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBangle\fP\&. 
.br
\fIN\fP Nr of angles in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these angles are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBangle_err_ok\fP or <0 on error (see \fBangle_err\fP) 
.RE
.PP

.SS "int angle_evalf (struct \fBangle\fP *a, intN, struct \fBengine\fP *e, \fBFPTYPE\fP *f, double *epot_out)"

.PP
Evaluate a list of angleed interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBangle\fP\&. 
.br
\fIN\fP Nr of angles in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these angles are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
This function differs from \fBangle_eval\fP in that the forces are added to the array \fCf\fP instead of directly in the particle data\&.
.PP
\fBReturns:\fP
.RS 4
\fBangle_err_ok\fP or <0 on error (see \fBangle_err\fP) 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int angle_err"
ID of the last error
.PP
The ID of the last error\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
