.TH "angle" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
angle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <angle\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "int \fBk\fP"
.br
.ti -1c
.RI "int \fBpid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The angle structure 
.SH "Field Documentation"
.PP 
.SS "int i"

.SS "int j"

.SS "int k"

.SS "int pid"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
