.TH "btree" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
btree \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <btree\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBbtree_node\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBbtree_node\fP * \fBcache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The btree itself\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBbtree_node\fP* cache"

.SS "struct \fBbtree_node\fP* first"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
