.TH "cell" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cell \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cell\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBloc\fP [3]"
.br
.ti -1c
.RI "double \fBorigin\fP [3]"
.br
.ti -1c
.RI "double \fBdim\fP [3]"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "struct \fBpart\fP * \fBparts\fP"
.br
.ti -1c
.RI "double \fBepot\fP"
.br
.ti -1c
.RI "struct \fBpart\fP * \fBincomming\fP"
.br
.ti -1c
.RI "int \fBincomming_size\fP"
.br
.ti -1c
.RI "int \fBincomming_count\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBcell_mutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcell_cond\fP"
.br
.ti -1c
.RI "\fBFPTYPE\fP * \fBoldx\fP"
.br
.ti -1c
.RI "int \fBoldx_size\fP"
.br
.ti -1c
.RI "int \fBnodeID\fP"
.br
.ti -1c
.RI "unsigned int * \fBsortlist\fP"
.br
.ti -1c
.RI "struct \fBtask\fP * \fBsort\fP"
.br
.ti -1c
.RI "int \fBGPUID\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t cell_cond"

.SS "pthread_mutex_t cell_mutex"

.SS "int count"

.SS "double dim[3]"

.SS "double epot"

.SS "unsigned int flags"

.SS "int GPUID"

.SS "int id"

.SS "struct \fBpart\fP* incomming"

.SS "int incomming_count"

.SS "int incomming_size"

.SS "int loc[3]"

.SS "int nodeID"

.SS "\fBFPTYPE\fP* oldx"

.SS "int oldx_size"

.SS "double origin[3]"

.SS "struct \fBpart\fP* parts"

.SS "int size"

.SS "struct \fBtask\fP* sort"

.SS "unsigned int* sortlist"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
