.TH "/home/stephan/code/unversioned/mdcore-0.1.7/src/cutil_math.h" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephan/code/unversioned/mdcore-0.1.7/src/cutil_math.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cuda_runtime\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBuint\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBushort\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBfminf\fP (float a, float b)"
.br
.ti -1c
.RI "float \fBfmaxf\fP (float a, float b)"
.br
.ti -1c
.RI "int \fBmax\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBmin\fP (int a, int b)"
.br
.ti -1c
.RI "float \fBrsqrtf\fP (float \fBx\fP)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBmake_float2\fP (float s)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBmake_float2\fP (float3 a)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBmake_float2\fP (int2 a)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBmake_float2\fP (uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmake_int2\fP (int s)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmake_int2\fP (int3 a)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmake_int2\fP (uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmake_int2\fP (float2 a)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBmake_uint2\fP (\fBuint\fP s)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBmake_uint2\fP (uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBmake_uint2\fP (int2 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (float s)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (float2 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (float2 a, float s)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (float4 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (int3 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBmake_float3\fP (uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmake_int3\fP (int s)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmake_int3\fP (int2 a)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmake_int3\fP (int2 a, int s)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmake_int3\fP (uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmake_int3\fP (float3 a)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmake_uint3\fP (\fBuint\fP s)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmake_uint3\fP (uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmake_uint3\fP (uint2 a, \fBuint\fP s)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmake_uint3\fP (uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmake_uint3\fP (int3 a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBmake_float4\fP (float s)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBmake_float4\fP (float3 a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBmake_float4\fP (float3 a, float w)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBmake_float4\fP (int4 a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBmake_float4\fP (uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmake_int4\fP (int s)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmake_int4\fP (int3 a)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmake_int4\fP (int3 a, int w)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmake_int4\fP (uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmake_int4\fP (float4 a)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmake_uint4\fP (\fBuint\fP s)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmake_uint4\fP (uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmake_uint4\fP (uint3 a, \fBuint\fP w)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmake_uint4\fP (int4 a)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator-\fP (float2 &a)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator-\fP (int2 &a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator-\fP (float3 &a)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator-\fP (int3 &a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator-\fP (float4 &a)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator-\fP (int4 &a)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator+\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float2 &a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator+\fP (float2 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator+\fP (float b, float2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float2 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator+\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int2 &a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator+\fP (int2 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator+\fP (int b, int2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int2 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator+\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint2 &a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator+\fP (uint2 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator+\fP (\fBuint\fP b, uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint2 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator+\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float3 &a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator+\fP (float3 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float3 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator+\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int3 &a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator+\fP (int3 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int3 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator+\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint3 &a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator+\fP (uint3 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint3 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator+\fP (int b, int3 a)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator+\fP (\fBuint\fP b, uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator+\fP (float b, float3 a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator+\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float4 &a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator+\fP (float4 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator+\fP (float b, float4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (float4 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator+\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int4 &a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator+\fP (int4 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator+\fP (int b, int4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (int4 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator+\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint4 &a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator+\fP (uint4 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator+\fP (\fBuint\fP b, uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator+=\fP (uint4 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator-\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float2 &a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator-\fP (float2 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator-\fP (float b, float2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float2 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator-\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int2 &a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator-\fP (int2 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator-\fP (int b, int2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int2 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator-\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint2 &a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator-\fP (uint2 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator-\fP (\fBuint\fP b, uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint2 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator-\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float3 &a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator-\fP (float3 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator-\fP (float b, float3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float3 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator-\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int3 &a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator-\fP (int3 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator-\fP (int b, int3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int3 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator-\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint3 &a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator-\fP (uint3 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator-\fP (\fBuint\fP b, uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint3 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator-\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float4 &a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator-\fP (float4 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (float4 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator-\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int4 &a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator-\fP (int4 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator-\fP (int b, int4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (int4 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator-\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint4 &a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator-\fP (uint4 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator-\fP (\fBuint\fP b, uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator-=\fP (uint4 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator*\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float2 &a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator*\fP (float2 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator*\fP (float b, float2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float2 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator*\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int2 &a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator*\fP (int2 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBoperator*\fP (int b, int2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int2 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator*\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint2 &a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator*\fP (uint2 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBoperator*\fP (\fBuint\fP b, uint2 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint2 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator*\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float3 &a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator*\fP (float3 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator*\fP (float b, float3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float3 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator*\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int3 &a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator*\fP (int3 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBoperator*\fP (int b, int3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int3 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator*\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint3 &a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator*\fP (uint3 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBoperator*\fP (\fBuint\fP b, uint3 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint3 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator*\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float4 &a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator*\fP (float4 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator*\fP (float b, float4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (float4 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator*\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int4 &a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator*\fP (int4 a, int b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBoperator*\fP (int b, int4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (int4 &a, int b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator*\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint4 &a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator*\fP (uint4 a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBoperator*\fP (\fBuint\fP b, uint4 a)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator*=\fP (uint4 &a, \fBuint\fP b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator/\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float2 &a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator/\fP (float2 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float2 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBoperator/\fP (float b, float2 a)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator/\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float3 &a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator/\fP (float3 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float3 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBoperator/\fP (float b, float3 a)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator/\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float4 &a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator/\fP (float4 a, float b)"
.br
.ti -1c
.RI "__host__ __device__ void \fBoperator/=\fP (float4 &a, float b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBoperator/\fP (float b, float4 a)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfminf\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfminf\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfminf\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmin\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmin\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmin\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBmin\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmin\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmin\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfmaxf\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfmaxf\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfmaxf\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBmax\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBmax\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBmax\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ uint2 \fBmax\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ uint3 \fBmax\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ uint4 \fBmax\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__device__ __host__ float \fBlerp\fP (float a, float b, float t)"
.br
.ti -1c
.RI "__device__ __host__ float2 \fBlerp\fP (float2 a, float2 b, float t)"
.br
.ti -1c
.RI "__device__ __host__ float3 \fBlerp\fP (float3 a, float3 b, float t)"
.br
.ti -1c
.RI "__device__ __host__ float4 \fBlerp\fP (float4 a, float4 b, float t)"
.br
.ti -1c
.RI "__device__ __host__ float \fBclamp\fP (float \fBf\fP, float a, float b)"
.br
.ti -1c
.RI "__device__ __host__ int \fBclamp\fP (int \fBf\fP, int a, int b)"
.br
.ti -1c
.RI "__device__ __host__ \fBuint\fP \fBclamp\fP (\fBuint\fP \fBf\fP, \fBuint\fP a, \fBuint\fP b)"
.br
.ti -1c
.RI "__device__ __host__ float2 \fBclamp\fP (float2 v, float a, float b)"
.br
.ti -1c
.RI "__device__ __host__ float2 \fBclamp\fP (float2 v, float2 a, float2 b)"
.br
.ti -1c
.RI "__device__ __host__ float3 \fBclamp\fP (float3 v, float a, float b)"
.br
.ti -1c
.RI "__device__ __host__ float3 \fBclamp\fP (float3 v, float3 a, float3 b)"
.br
.ti -1c
.RI "__device__ __host__ float4 \fBclamp\fP (float4 v, float a, float b)"
.br
.ti -1c
.RI "__device__ __host__ float4 \fBclamp\fP (float4 v, float4 a, float4 b)"
.br
.ti -1c
.RI "__device__ __host__ int2 \fBclamp\fP (int2 v, int a, int b)"
.br
.ti -1c
.RI "__device__ __host__ int2 \fBclamp\fP (int2 v, int2 a, int2 b)"
.br
.ti -1c
.RI "__device__ __host__ int3 \fBclamp\fP (int3 v, int a, int b)"
.br
.ti -1c
.RI "__device__ __host__ int3 \fBclamp\fP (int3 v, int3 a, int3 b)"
.br
.ti -1c
.RI "__device__ __host__ int4 \fBclamp\fP (int4 v, int a, int b)"
.br
.ti -1c
.RI "__device__ __host__ int4 \fBclamp\fP (int4 v, int4 a, int4 b)"
.br
.ti -1c
.RI "__device__ __host__ uint2 \fBclamp\fP (uint2 v, \fBuint\fP a, \fBuint\fP b)"
.br
.ti -1c
.RI "__device__ __host__ uint2 \fBclamp\fP (uint2 v, uint2 a, uint2 b)"
.br
.ti -1c
.RI "__device__ __host__ uint3 \fBclamp\fP (uint3 v, \fBuint\fP a, \fBuint\fP b)"
.br
.ti -1c
.RI "__device__ __host__ uint3 \fBclamp\fP (uint3 v, uint3 a, uint3 b)"
.br
.ti -1c
.RI "__device__ __host__ uint4 \fBclamp\fP (uint4 v, \fBuint\fP a, \fBuint\fP b)"
.br
.ti -1c
.RI "__device__ __host__ uint4 \fBclamp\fP (uint4 v, uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ float \fBdot\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float \fBdot\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float \fBdot\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ int \fBdot\fP (int2 a, int2 b)"
.br
.ti -1c
.RI "__host__ __device__ int \fBdot\fP (int3 a, int3 b)"
.br
.ti -1c
.RI "__host__ __device__ int \fBdot\fP (int4 a, int4 b)"
.br
.ti -1c
.RI "__host__ __device__ \fBuint\fP \fBdot\fP (uint2 a, uint2 b)"
.br
.ti -1c
.RI "__host__ __device__ \fBuint\fP \fBdot\fP (uint3 a, uint3 b)"
.br
.ti -1c
.RI "__host__ __device__ \fBuint\fP \fBdot\fP (uint4 a, uint4 b)"
.br
.ti -1c
.RI "__host__ __device__ float \fBlength\fP (float2 v)"
.br
.ti -1c
.RI "__host__ __device__ float \fBlength\fP (float3 v)"
.br
.ti -1c
.RI "__host__ __device__ float \fBlength\fP (float4 v)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBnormalize\fP (float2 v)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBnormalize\fP (float3 v)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBnormalize\fP (float4 v)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfloorf\fP (float2 v)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfloorf\fP (float3 v)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfloorf\fP (float4 v)"
.br
.ti -1c
.RI "__host__ __device__ float \fBfracf\fP (float v)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfracf\fP (float2 v)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfracf\fP (float3 v)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfracf\fP (float4 v)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfmodf\fP (float2 a, float2 b)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfmodf\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfmodf\fP (float4 a, float4 b)"
.br
.ti -1c
.RI "__host__ __device__ float2 \fBfabs\fP (float2 v)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBfabs\fP (float3 v)"
.br
.ti -1c
.RI "__host__ __device__ float4 \fBfabs\fP (float4 v)"
.br
.ti -1c
.RI "__host__ __device__ int2 \fBabs\fP (int2 v)"
.br
.ti -1c
.RI "__host__ __device__ int3 \fBabs\fP (int3 v)"
.br
.ti -1c
.RI "__host__ __device__ int4 \fBabs\fP (int4 v)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBreflect\fP (float3 i, float3 n)"
.br
.ti -1c
.RI "__host__ __device__ float3 \fBcross\fP (float3 a, float3 b)"
.br
.ti -1c
.RI "__device__ __host__ float \fBsmoothstep\fP (float a, float b, float \fBx\fP)"
.br
.ti -1c
.RI "__device__ __host__ float2 \fBsmoothstep\fP (float2 a, float2 b, float2 \fBx\fP)"
.br
.ti -1c
.RI "__device__ __host__ float3 \fBsmoothstep\fP (float3 a, float3 b, float3 \fBx\fP)"
.br
.ti -1c
.RI "__device__ __host__ float4 \fBsmoothstep\fP (float4 a, float4 b, float4 \fBx\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBuint\fP"

.SS "typedef unsigned short \fBushort\fP"

.SH "Function Documentation"
.PP 
.SS "__host__ __device__ int2 abs (int2v)\fC [inline]\fP"

.SS "__host__ __device__ int3 abs (int3v)\fC [inline]\fP"

.SS "__host__ __device__ int4 abs (int4v)\fC [inline]\fP"

.SS "__device__ __host__ float clamp (floatf, floata, floatb)\fC [inline]\fP"

.SS "__device__ __host__ int clamp (intf, inta, intb)\fC [inline]\fP"

.SS "__device__ __host__ \fBuint\fP clamp (\fBuint\fPf, \fBuint\fPa, \fBuint\fPb)\fC [inline]\fP"

.SS "__device__ __host__ float2 clamp (float2v, floata, floatb)\fC [inline]\fP"

.SS "__device__ __host__ float2 clamp (float2v, float2a, float2b)\fC [inline]\fP"

.SS "__device__ __host__ float3 clamp (float3v, floata, floatb)\fC [inline]\fP"

.SS "__device__ __host__ float3 clamp (float3v, float3a, float3b)\fC [inline]\fP"

.SS "__device__ __host__ float4 clamp (float4v, floata, floatb)\fC [inline]\fP"

.SS "__device__ __host__ float4 clamp (float4v, float4a, float4b)\fC [inline]\fP"

.SS "__device__ __host__ int2 clamp (int2v, inta, intb)\fC [inline]\fP"

.SS "__device__ __host__ int2 clamp (int2v, int2a, int2b)\fC [inline]\fP"

.SS "__device__ __host__ int3 clamp (int3v, inta, intb)\fC [inline]\fP"

.SS "__device__ __host__ int3 clamp (int3v, int3a, int3b)\fC [inline]\fP"

.SS "__device__ __host__ int4 clamp (int4v, inta, intb)\fC [inline]\fP"

.SS "__device__ __host__ int4 clamp (int4v, int4a, int4b)\fC [inline]\fP"

.SS "__device__ __host__ uint2 clamp (uint2v, \fBuint\fPa, \fBuint\fPb)\fC [inline]\fP"

.SS "__device__ __host__ uint2 clamp (uint2v, uint2a, uint2b)\fC [inline]\fP"

.SS "__device__ __host__ uint3 clamp (uint3v, \fBuint\fPa, \fBuint\fPb)\fC [inline]\fP"

.SS "__device__ __host__ uint3 clamp (uint3v, uint3a, uint3b)\fC [inline]\fP"

.SS "__device__ __host__ uint4 clamp (uint4v, \fBuint\fPa, \fBuint\fPb)\fC [inline]\fP"

.SS "__device__ __host__ uint4 clamp (uint4v, uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ float3 cross (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float dot (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float dot (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float dot (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ int dot (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int dot (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int dot (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ \fBuint\fP dot (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ \fBuint\fP dot (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ \fBuint\fP dot (uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ float2 fabs (float2v)\fC [inline]\fP"

.SS "__host__ __device__ float3 fabs (float3v)\fC [inline]\fP"

.SS "__host__ __device__ float4 fabs (float4v)\fC [inline]\fP"

.SS "__host__ __device__ float2 floorf (float2v)\fC [inline]\fP"

.SS "__host__ __device__ float3 floorf (float3v)\fC [inline]\fP"

.SS "__host__ __device__ float4 floorf (float4v)\fC [inline]\fP"

.SS "float fmaxf (floata, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 fmaxf (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float3 fmaxf (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float4 fmaxf (float4a, float4b)\fC [inline]\fP"

.SS "float fminf (floata, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 fminf (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float3 fminf (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float4 fminf (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float2 fmodf (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float3 fmodf (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float4 fmodf (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float fracf (floatv)\fC [inline]\fP"

.SS "__host__ __device__ float2 fracf (float2v)\fC [inline]\fP"

.SS "__host__ __device__ float3 fracf (float3v)\fC [inline]\fP"

.SS "__host__ __device__ float4 fracf (float4v)\fC [inline]\fP"

.SS "__host__ __device__ float length (float2v)\fC [inline]\fP"

.SS "__host__ __device__ float length (float3v)\fC [inline]\fP"

.SS "__host__ __device__ float length (float4v)\fC [inline]\fP"

.SS "__device__ __host__ float lerp (floata, floatb, floatt)\fC [inline]\fP"

.SS "__device__ __host__ float2 lerp (float2a, float2b, floatt)\fC [inline]\fP"

.SS "__device__ __host__ float3 lerp (float3a, float3b, floatt)\fC [inline]\fP"

.SS "__device__ __host__ float4 lerp (float4a, float4b, floatt)\fC [inline]\fP"

.SS "__host__ __device__ float2 make_float2 (floats)\fC [inline]\fP"

.SS "__host__ __device__ float2 make_float2 (float3a)\fC [inline]\fP"

.SS "__host__ __device__ float2 make_float2 (int2a)\fC [inline]\fP"

.SS "__host__ __device__ float2 make_float2 (uint2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (floats)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (float2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (float2a, floats)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (float4a)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (int3a)\fC [inline]\fP"

.SS "__host__ __device__ float3 make_float3 (uint3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 make_float4 (floats)\fC [inline]\fP"

.SS "__host__ __device__ float4 make_float4 (float3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 make_float4 (float3a, floatw)\fC [inline]\fP"

.SS "__host__ __device__ float4 make_float4 (int4a)\fC [inline]\fP"

.SS "__host__ __device__ float4 make_float4 (uint4a)\fC [inline]\fP"

.SS "__host__ __device__ int2 make_int2 (ints)\fC [inline]\fP"

.SS "__host__ __device__ int2 make_int2 (int3a)\fC [inline]\fP"

.SS "__host__ __device__ int2 make_int2 (uint2a)\fC [inline]\fP"

.SS "__host__ __device__ int2 make_int2 (float2a)\fC [inline]\fP"

.SS "__host__ __device__ int3 make_int3 (ints)\fC [inline]\fP"

.SS "__host__ __device__ int3 make_int3 (int2a)\fC [inline]\fP"

.SS "__host__ __device__ int3 make_int3 (int2a, ints)\fC [inline]\fP"

.SS "__host__ __device__ int3 make_int3 (uint3a)\fC [inline]\fP"

.SS "__host__ __device__ int3 make_int3 (float3a)\fC [inline]\fP"

.SS "__host__ __device__ int4 make_int4 (ints)\fC [inline]\fP"

.SS "__host__ __device__ int4 make_int4 (int3a)\fC [inline]\fP"

.SS "__host__ __device__ int4 make_int4 (int3a, intw)\fC [inline]\fP"

.SS "__host__ __device__ int4 make_int4 (uint4a)\fC [inline]\fP"

.SS "__host__ __device__ int4 make_int4 (float4a)\fC [inline]\fP"

.SS "__host__ __device__ uint2 make_uint2 (\fBuint\fPs)\fC [inline]\fP"

.SS "__host__ __device__ uint2 make_uint2 (uint3a)\fC [inline]\fP"

.SS "__host__ __device__ uint2 make_uint2 (int2a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 make_uint3 (\fBuint\fPs)\fC [inline]\fP"

.SS "__host__ __device__ uint3 make_uint3 (uint2a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 make_uint3 (uint2a, \fBuint\fPs)\fC [inline]\fP"

.SS "__host__ __device__ uint3 make_uint3 (uint4a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 make_uint3 (int3a)\fC [inline]\fP"

.SS "__host__ __device__ uint4 make_uint4 (\fBuint\fPs)\fC [inline]\fP"

.SS "__host__ __device__ uint4 make_uint4 (uint3a)\fC [inline]\fP"

.SS "__host__ __device__ uint4 make_uint4 (uint3a, \fBuint\fPw)\fC [inline]\fP"

.SS "__host__ __device__ uint4 make_uint4 (int4a)\fC [inline]\fP"

.SS "int max (inta, intb)\fC [inline]\fP"

.SS "__host__ __device__ int2 max (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int3 max (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int4 max (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ uint2 max (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ uint3 max (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ uint4 max (uint4a, uint4b)\fC [inline]\fP"

.SS "int min (inta, intb)\fC [inline]\fP"

.SS "__host__ __device__ int2 min (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int3 min (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int4 min (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ uint2 min (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ uint3 min (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ uint4 min (uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ float2 normalize (float2v)\fC [inline]\fP"

.SS "__host__ __device__ float3 normalize (float3v)\fC [inline]\fP"

.SS "__host__ __device__ float4 normalize (float4v)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator* (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator* (float2a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator* (floatb, float2a)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator* (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator* (int2a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator* (intb, int2a)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator* (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator* (uint2a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator* (\fBuint\fPb, uint2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator* (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator* (float3a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator* (floatb, float3a)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator* (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator* (int3a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator* (intb, int3a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator* (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator* (uint3a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator* (\fBuint\fPb, uint3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator* (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator* (float4a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator* (floatb, float4a)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator* (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator* (int4a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator* (intb, int4a)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator* (uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator* (uint4a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator* (\fBuint\fPb, uint4a)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float2 &a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float2 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int2 &a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int2 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint2 &a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint2 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float3 &a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float3 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int3 &a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int3 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint3 &a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint3 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float4 &a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (float4 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int4 &a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (int4 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint4 &a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator*= (uint4 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator+ (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator+ (float2a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator+ (floatb, float2a)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator+ (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator+ (int2a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator+ (intb, int2a)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator+ (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator+ (uint2a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator+ (\fBuint\fPb, uint2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator+ (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator+ (float3a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator+ (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator+ (int3a, intb)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator+ (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator+ (uint3a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator+ (intb, int3a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator+ (\fBuint\fPb, uint3a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator+ (floatb, float3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator+ (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator+ (float4a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator+ (floatb, float4a)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator+ (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator+ (int4a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator+ (intb, int4a)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator+ (uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator+ (uint4a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator+ (\fBuint\fPb, uint4a)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float2 &a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float2 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int2 &a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int2 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint2 &a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint2 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float3 &a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float3 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int3 &a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int3 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint3 &a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint3 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float4 &a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (float4 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int4 &a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (int4 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint4 &a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator+= (uint4 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator- (float2 &a)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator- (int2 &a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator- (float3 &a)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator- (int3 &a)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator- (float4 &a)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator- (int4 &a)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator- (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator- (float2a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator- (floatb, float2a)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator- (int2a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator- (int2a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int2 operator- (intb, int2a)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator- (uint2a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator- (uint2a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint2 operator- (\fBuint\fPb, uint2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator- (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator- (float3a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator- (floatb, float3a)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator- (int3a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator- (int3a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int3 operator- (intb, int3a)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator- (uint3a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator- (uint3a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint3 operator- (\fBuint\fPb, uint3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator- (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator- (float4a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator- (int4a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator- (int4a, intb)\fC [inline]\fP"

.SS "__host__ __device__ int4 operator- (intb, int4a)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator- (uint4a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator- (uint4a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ uint4 operator- (\fBuint\fPb, uint4a)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float2 &a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float2 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int2 &a, int2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int2 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint2 &a, uint2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint2 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float3 &a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float3 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int3 &a, int3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int3 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint3 &a, uint3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint3 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float4 &a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (float4 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int4 &a, int4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (int4 &a, intb)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint4 &a, uint4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator-= (uint4 &a, \fBuint\fPb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator/ (float2a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator/ (float2a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float2 operator/ (floatb, float2a)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator/ (float3a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator/ (float3a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float3 operator/ (floatb, float3a)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator/ (float4a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator/ (float4a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float4 operator/ (floatb, float4a)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float2 &a, float2b)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float2 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float3 &a, float3b)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float3 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float4 &a, float4b)\fC [inline]\fP"

.SS "__host__ __device__ void operator/= (float4 &a, floatb)\fC [inline]\fP"

.SS "__host__ __device__ float3 reflect (float3i, float3n)\fC [inline]\fP"

.SS "float rsqrtf (floatx)\fC [inline]\fP"

.SS "__device__ __host__ float smoothstep (floata, floatb, floatx)\fC [inline]\fP"

.SS "__device__ __host__ float2 smoothstep (float2a, float2b, float2x)\fC [inline]\fP"

.SS "__device__ __host__ float3 smoothstep (float3a, float3b, float3x)\fC [inline]\fP"

.SS "__device__ __host__ float4 smoothstep (float4a, float4b, float4x)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
