.TH "/home/stephan/code/unversioned/mdcore-0.1.7/src/dihedral.h" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephan/code/unversioned/mdcore-0.1.7/src/dihedral.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdihedral\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdihedral_err_ok\fP   0"
.br
.ti -1c
.RI "#define \fBdihedral_err_null\fP   -1"
.br
.ti -1c
.RI "#define \fBdihedral_err_malloc\fP   -2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdihedral_eval\fP (struct \fBdihedral\fP *d, int N, struct \fBengine\fP *\fBe\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of dihedraled interactions\&. \fP"
.ti -1c
.RI "int \fBdihedral_evalf\fP (struct \fBdihedral\fP *d, int N, struct \fBengine\fP *\fBe\fP, \fBFPTYPE\fP *\fBf\fP, double *epot_out)"
.br
.RI "\fIEvaluate a list of dihedraled interactions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBdihedral_err\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define dihedral_err_malloc   -2"

.SS "#define dihedral_err_null   -1"

.SS "#define dihedral_err_ok   0"

.SH "Function Documentation"
.PP 
.SS "int dihedral_eval (struct \fBdihedral\fP *d, intN, struct \fBengine\fP *e, double *epot_out)"

.PP
Evaluate a list of dihedraled interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBdihedral\fP\&. 
.br
\fIN\fP Nr of dihedrals in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these dihedrals are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBdihedral_err_ok\fP or <0 on error (see \fBdihedral_err\fP) 
.RE
.PP

.SS "int dihedral_evalf (struct \fBdihedral\fP *d, intN, struct \fBengine\fP *e, \fBFPTYPE\fP *f, double *epot_out)"

.PP
Evaluate a list of dihedraled interactions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Pointer to an array of \fBdihedral\fP\&. 
.br
\fIN\fP Nr of dihedrals in \fCb\fP\&. 
.br
\fIe\fP Pointer to the \fBengine\fP in which these dihedrals are evaluated\&. 
.br
\fIepot_out\fP Pointer to a double in which to aggregate the potential energy\&.
.RE
.PP
This function differs from \fBdihedral_eval\fP in that the forces are added to the array \fCf\fP instead of directly in the particle data\&.
.PP
\fBReturns:\fP
.RS 4
\fBdihedral_err_ok\fP or <0 on error (see \fBdihedral_err\fP) 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int dihedral_err"
ID of the last error
.PP
The ID of the last error\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
