.TH "engine_comm" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engine_comm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <engine\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int * \fBcellid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure storing which cells to send/receive to/from another node\&. 
.SH "Field Documentation"
.PP 
.SS "int* cellid"

.SS "int count"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
