.TH "/home/stephan/code/unversioned/mdcore-0.1.7/src/errs.c" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/stephan/code/unversioned/mdcore-0.1.7/src/errs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'errs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBerrs_clear\fP ()"
.br
.RI "\fIRe-set the error stack\&. \fP"
.ti -1c
.RI "int \fBerrs_dump\fP (FILE *out)"
.br
.RI "\fIPrint the error stack out to the given FILE pointer\&. \fP"
.ti -1c
.RI "int \fBerrs_register\fP (int \fBid\fP, const char *\fBmsg\fP, int \fBline\fP, const char *\fBfunc\fP, char *\fBfile\fP)"
.br
.RI "\fIDump an error onto the stack\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrs_err\fP = \fBerrs_err_ok\fP"
.br
.ti -1c
.RI "const char * \fBerrs_err_msg\fP []"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBid\fP"
.br
.ti -1c
.RI "   int \fBline\fP"
.br
.ti -1c
.RI "   const char * \fBmsg\fP"
.br
.ti -1c
.RI "   const char * \fBfunc\fP"
.br
.ti -1c
.RI "   const char * \fBfile\fP"
.br
.ti -1c
.RI "} \fBerrs_stack\fP [\fBerrs_maxstack\fP]"
.br
.ti -1c
.RI "int \fBerrs_count\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void errs_clear ()"

.PP
Re-set the error stack\&. 
.SS "int errs_dump (FILE *out)"

.PP
Print the error stack out to the given FILE pointer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIout\fP A pointer to a FILE structure\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBerrs_err_ok\fP or < 0 on failure\&. 
.RE
.PP

.SS "int errs_register (intid, const char *msg, intline, const char *func, char *file)"

.PP
Dump an error onto the stack\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP An error identifier that will be returned\&. 
.br
\fImsg\fP A pointer to a string containing a descriptive error message\&. 
.br
\fIline\fP The line on which the error occured\&. 
.br
\fIfunc\fP The name of the function in which the error occured\&. 
.br
\fIfile\fP The name of the file in which the error occured\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The value of \fCid\fP\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "int errs_count = 0"

.SS "int errs_err = \fBerrs_err_ok\fP"

.SS "const char* errs_err_msg[]"
\fBInitial value:\fP
.PP
.nf
= {
    "All is well\&.",
    "An IO-error has occurred\&." }
.fi
.SS "struct { \&.\&.\&. }   errs_stack[ \fBerrs_maxstack\fP ]"

.SS "const char * file"

.SS "const char * func"

.SS "int id"

.SS "int line"

.SS "const char* msg"

.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
