.TH "exclusion" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exclusion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exclusion\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The exclusion structure 
.SH "Field Documentation"
.PP 
.SS "int i"

.SS "int j"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
