.TH "part_type" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
part_type \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <part\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "double \fBmass\fP"
.br
.ti -1c
.RI "double \fBimass\fP"
.br
.ti -1c
.RI "double \fBcharge\fP"
.br
.ti -1c
.RI "double \fBeps\fP"
.br
.ti -1c
.RI "double \fBrmin\fP"
.br
.ti -1c
.RI "char \fBname\fP [64]"
.br
.ti -1c
.RI "char \fBname2\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing information on each particle species\&. 
.SH "Field Documentation"
.PP 
.SS "double charge"

.SS "double eps"
Nonbonded interaction parameters\&. 
.SS "int id"
ID of this type 
.SS "double imass"

.SS "double mass"
Constant physical characteristics 
.SS "char name[64]"
Name of this paritcle type\&. 
.SS "char name2[64]"

.SS "double rmin"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
