.TH "potential" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
potential \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <potential\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFPTYPE\fP \fBalpha\fP [4]"
.br
.ti -1c
.RI "\fBFPTYPE\fP * \fBc\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBpotential\fP structure\&. 
.SH "Field Documentation"
.PP 
.SS "double a"
Interval edges\&. 
.SS "\fBFPTYPE\fP alpha[4]"
Coefficients for the interval transform\&. 
.SS "double b"

.SS "\fBFPTYPE\fP* c"
The coefficients\&. 
.SS "unsigned int flags"
Flags\&. 
.SS "int n"
Nr of intervals\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
