.TH "queue" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "struct \fBtask\fP * \fBtasks\fP"
.br
.ti -1c
.RI "struct \fBspace\fP * \fBspace\fP"
.br
.ti -1c
.RI "int * \fBind\fP"
.br
.ti -1c
.RI "int \fBnext\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBlock_type\fP \fBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The queue structure 
.SH "Field Documentation"
.PP 
.SS "int count"

.SS "int* ind"

.SS "\fBlock_type\fP lock"

.SS "int next"

.SS "int size"

.SS "struct \fBspace\fP* \fBspace\fP"

.SS "struct \fBtask\fP* tasks"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
