.TH "queue_cuda" 3 "Mon Jan 6 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue_cuda \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runner_cuda\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "volatile int \fBcount\fP"
.br
.ti -1c
.RI "volatile int \fBrec_count\fP"
.br
.ti -1c
.RI "volatile int * \fBdata\fP"
.br
.ti -1c
.RI "volatile int * \fBrec_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for a task queue\&. 
.SH "Field Documentation"
.PP 
.SS "volatile int count"

.SS "volatile int* data"

.SS "int first"

.SS "int last"

.SS "volatile int rec_count"

.SS "volatile int* rec_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
