.TH "runner_fifo" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runner_fifo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runner\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int * \fBdata\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t cond"

.SS "int count"

.SS "int* data"

.SS "int first"

.SS "int last"

.SS "pthread_mutex_t mutex"

.SS "int size"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
