.TH "runner" 3 "Thu Apr 24 2014" "Version 0.1.5" "mdcore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
runner \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <runner\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBengine\fP * \fBe\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "pthread_t \fBthread\fP"
.br
.ti -1c
.RI "int \fBerr\fP"
.br
.ti -1c
.RI "double \fBepot\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBengine\fP* e"

.SS "double epot"
Accumulated potential energy by this runner\&. 
.SS "int err"
ID of the last error on this runner\&. 
.SS "int id"

.SS "pthread_t thread"


.SH "Author"
.PP 
Generated automatically by Doxygen for mdcore from the source code\&.
